### ISSUE TITLE
Incorrect parsing of graphite tags with equal signs in value

### ISSUE THREAD

**Issue by litleleprikon** [moira-alert/moira#489]
# BUG REPORT

## What did you expect to see?
Metrics that have equal signs in tag values should be accepted by Moira. For example `my.series;tag1=value1;tag2=value=2` is a valid metric with tags following carbon specification.

https://github.com/graphite-project/graphite-web/blob/7149908675664f341c91dcacfff83c55505564fa/docs/tags.rst#carbon

## What did you see instead?
Moira filters will drop this metric as an invalid with following message:

```
INFO    cannot parse input: cannot parse metric: 'my.series;tag1=value1;tag2=value=2' (too many equal-separated items: 'tag2=value=2')
```

**Comment by litleleprikon** [comment]
The fix for this issue is a remove an `if` here https://github.com/moira-alert/moira/blob/master/filter/metrics_parser.go#L96-L99

We also need to cover cases with equals sign in tag value with test.

**Comment by idoqo** [comment]
Hi @litleleprikon, I was trying to get familiar with the codebase and would love to take a shot at this.

The tests still fail after removing the mentioned `if` statement though, so I was wondering what would be the best way to leave all equal signs after the first one untouched because:

Given a sample input, say, 
```"One.two.three;four=five;six=seven=eight 123 1234567890"```,
- `labelBytesScanner` uses the `=` as the delimiter, so removing the `if` condition returns the label as `'map[string]string{"four":"five", "six":"seven"}'` (ignoring the equal sign).
- Appending `labelBytesScanner.Next()...` doesn't work as it also ignores the equal sign and returns `'One.two.three;four=five;six=seveneightt'` instead.

**Comment by litleleprikon** [comment]
Hi @idoqo you are absolutely right. I will check your PR soon!
