### ISSUE TITLE
Slack notifier formatting not work

### ISSUE THREAD

**Issue by avinchakov** [moira-alert/moira#68]
Suddenly, the formatting of our application and bot messages stopped working. About 3-4 weeks ago. At the same time, the formatting works in the mobile application.

I suspect that the issue is the parameter here: [https://github.com/moira-alert/moira/blob/d2fed3254ce7e405f523f52261092c024d2e6d2d/senders/slack/slack.go#L65](https://github.com/moira-alert/moira/blob/d2fed3254ce7e405f523f52261092c024d2e6d2d/senders/slack/slack.go#L65)

The correct name for this parameter is "mrkdwn". You can find more details here: https://api.slack.com/docs/message-formatting

**Comment by kamaev** [comment]
Hi! Yes, applications must add key "mrkdwn":true to use Slack's markdown.
"Markdown" is parameter of PostMessageParameters struct from nlopes/slack library (https://github.com/nlopes/slack/blob/master/chat.go#L34) which actually uses "mrkdwn".
You also found this line because we fixed the issue with Slack's markdown in https://github.com/moira-alert/moira/commit/d2fed3254ce7e405f523f52261092c024d2e6d2d but unfortunately, we haven't tagged this yet so changes will take effect in the next release. But you also can get the latest docker image or build binary from latest master if you want to get the fixes right now

**Comment by avinchakov** [comment]
Oh, thank you. I will wait for it.
